server:
  port: 30002

spring:
  redis:
    host: localhost
    database: 1
    password: password
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true
