server:
  port: 30002


spring:
  redis:
    host: 10.60.64.66
    database: 1
    password: wssy001
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true