server:
  port: 30002


spring:
  redis:
    host: 10.60.64.66
    database: 1
    password: wssy001
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10

  data:
    mongodb:
      uri: mongodb://root:wssy001@10.60.64.66:27017
      database: back_up
      repositories:
        type: none

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: 10.60.64.66:39876
  producer:
    group: group1
